name: ${rootProject.name.capitalize()}
version: $version
main: $group.${rootProject.name}.plugin.${rootProject.name.capitalize()}Plugin
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.20
  - io.github.monun:tap:4.0.0
  - io.github.monun:kommand:2.0.1