name: ${rootProject.name.capitalize()}
version: $version
main: $group.${rootProject.name}.plugin.${rootProject.name.capitalize()}Plugin
libraries:
  - io.github.monun:tap:4.1.1
  - io.github.monun:kommand:2.1.0